// Fill out your copyright notice in the Description page of Project Settings.


#include "Debug/UELOGCategories.h"

TEAMASSIGNMENTFPS_API DEFINE_LOG_CATEGORY(UI_Log);

TEAMASSIGNMENTFPS_API DEFINE_LOG_CATEGORY(IMC_Log);

TEAMASSIGNMENTFPS_API DEFINE_LOG_CATEGORY(Controller_Log);

TEAMASSIGNMENTFPS_API DEFINE_LOG_CATEGORY(Camera_Log);

TEAMASSIGNMENTFPS_API DEFINE_LOG_CATEGORY(Movement_Log);

TEAMASSIGNMENTFPS_API DEFINE_LOG_CATEGORY(TimeManager_Log);